---
# This playbook deploys a equinox configution.
- hosts: all
  gather_facts: no
  vars:
    APP: ANSIBLE
    # E00
    INSTANCE_E00: 0
    SF_LISTNER_PORT: 2000
  tasks:
  - name: Copy & Edit equinox configuration
    #template:
    #  src: EQM/conf/app.E00.x.0
    #  dest: /opt/equinox/conf/app.E00.x.0
    #- lineinfile: dest=/opt/equinox/conf/app.E00.x.0  regexp="{{ APP }}" line={APP 
    template:
      src: EQM/conf/app.E00.x.0
      dest: /opt/equinox/conf/{{APP}}.E00.x.{{INSTANCE_E00}}
      owner: toro 
      group: root
      mode: 0644
    #- lineinfile: dest=/opt/equinox/conf/app.E00.x.0  regexp="\$\{INSTANCE_E00\}" line=0 
    #- lineinfile: dest=/opt/equinox/conf/app.E00.x.0  regexp="\$\{SF_LISTNER_PORT\}" line=2000
